FROM kalilinux/kali-rolling:latest

RUN apt update -y
RUN apt install curl -y
RUN apt install iputils-ping -y
RUN apt-get install nmap nikto ffuf -y
RUN apt-get install python3 python3-pip -y
RUN pip install requests
RUN apt-get install netcat-traditional -y
RUN apt-get install sqlmap -y
COPY start.sh /
COPY ./exploit /exploit

ENTRYPOINT [ "/start.sh" ]